### PR TITLE
Friendship v1

### PR DESCRIPTION
**Pull request by patriciachrysy**
- Created the friendship model
- Added the relationship between Users and Friendship
- Wrote the test cases for the User and Friendship models
Thanks for your review

### CODE REVIEW

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team      
#### Great Job so far, but there are a few more things required. 
### General
- [x] Lets include linter for this project.
- [x]  A meaningful description about the project should be included in the readme file .
- [x] Integration should be included.
* [x] User can see friendships requests 
* [x] User has to accept friendship request to start friendship 
* [x] User can reject a friendship request
* [x] There is a button to invite user to friendship on users list page and on single user page
* [x] Posts timeline includes posts written by logged-in user and their friends
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by dili021** [comment]
### Dear TSEs:
- We hope we have fulfilled all the necessary changes you have requested.
- Also added the likes and comments count
- Thank you again for your time!

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello Team!
### You have done really good so far :clap: However, you are required to make a minor adjustment.
- [ ] Add linter to your project and solve the raised issues
### Make the change and submit for another code review. good luck.
- Happy coding!

By Raymond
Slack @iamraymond

**Comment by dili021** [comment]
> Hello Team!
> 
> ### You have done really good so far  However, you are required to make a minor adjustment.
> * [ ]  Add linter to your project and solve the raised issues
> 
> ### Make the change and submit for another code review. good luck.
> * Happy coding!
> 
> By Raymond
> Slack @IAmRaymond

### Dear TSE
- Please consider what you wrote. The linter is working and the checks are passing. 

image

- We are trying to setup the linter on Github Actions but are having issues. This, however, is not required for a midway project: 

image

**Comment by patriciachrysy** [comment]
Dear TSE,
we even added the new configuration for or from Microverse so please make sure you take a close look before giving your review.
Thanks for your time

**Review by kobiyoyo — APPROVED** [review]
# Project Approved :thumbsup:
## Hello Team,  You have done a great job with this project. :clap:
#### You can go ahead and merge !!!

**Pull request closed without merging**
