### PR TITLE
draw the erd and added it to the project repo

### PR DESCRIPTION
**Pull request by patriciachrysy**
Created the diagram on Ludicart, exported it as pdf file and added it to the project in the docs directory.
Thanks for reviewing our diagram

### CODE REVIEW

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great Start @team :clap: :clap: However, some changes need to be applied in order to get approval for this milestone. Check :arrow_down: 

- **[REQUIRED]** Friendship_Request table is supposed to act as a join table that connects users with their friends. Doing one relationship between the two tables like you did won't allow you to add two foreign keys. Each association signifies a single relationship (either a sender or a receiver). You need two relationships, one for the sender of the friend request and the other for the receiver.

- **[SUGGESTION]** Also it's an ERD design convention to name join tables after their relationships, for this case it's better to name it "Friendship".

### That's it :relieved: When finished, kindly submit a code re-review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

**Comment by dili021** [comment]
### Updated the ERD 
- Change Friendship Request to Friendship
- include the second User-Friendship relation

**Comment by uryelah** [comment]
Hi **Patricia Manezeu & Stefan Dili**, I'm Sarah your reviewer for this PR 👩‍🚀 

Good job with your the join table.

There are still a couple of quick fields you missed, but you got this! 💪 

## Changes Required 🏗️ 🐛 💡

- [x] The User table has image_link column 

- [x] The Friendship table has status or confirmed column

- [x] Remember to connect the Like with the User

Example ERD:
erd


-----

 **Kindly fix the pointed out issues before requesting the next code review**

------------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by dili021** [comment]
### Dear TSE
- We have updated the ERD to fit the outlined requirements. Thank you for your time.

**Review by suretrust — APPROVED** [review]
Hi team, 👋 

### Great job implementing the suggested changes. 🙌 Let's get this merged! 👍 

_Good luck with your future projects and happy coding!_ 🎉

**Pull request merged**
